CREATE TABLE IF NOT EXISTS qualidades (
  id INT AUTO_INCREMENT PRIMARY KEY,
  altura DECIMAL(4,2) NOT NULL,
  espessura DECIMAL(4,2) NOT NULL,
  preenchimento INT NOT NULL,
  velocidade INT NOT NULL,
  temperatura_bico INT NOT NULL,
  temperatura_mesa INT NOT NULL,
  suporte INT NOT NULL,
  adesao INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
