CREATE TABLE `pedidos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `descricao` TEXT NULL,
  `status` ENUM(
    'analisando',
    'aguardando_pagamento',
    'aguardando_revisao',
    'na_fila',
    'em_impressao',
    'concluido',
    'falhou',
    'cancelado'
  ) NOT NULL DEFAULT 'analisando',
  `id_usuario` INT UNSIGNED NOT NULL,
  `id_material` INT UNSIGNED NOT NULL,
  `id_qualidade` INT UNSIGNED NOT NULL,
  `id_arquivo` INT UNSIGNED NOT NULL,
  `parametros` JSON NULL,
  `quantidade` INT UNSIGNED NOT NULL DEFAULT 1,
  `gcode_path` VARCHAR(512) NULL,
  `tempo_estimado_s` INT UNSIGNED NULL,
  `material_gramas` DECIMAL(12,4) NULL,
  `score_complexidade` DECIMAL(5,4) NULL,
  `motivo_complexidade` TEXT NULL,
  `motivo_falha` TEXT NULL,
  `motivo_cancelamento` TEXT NULL,
  `preco_base` DECIMAL(10,2) NULL,
  `taxa_complexidade` DECIMAL(10,2) NULL,
  `taxa_stripe` DECIMAL(10,2) NULL,
  `tempo_gcode_horas` DECIMAL(8,2) NULL,
  `prazo_entrega_horas` DECIMAL(8,2) NULL,
  `prazo_entrega` DATETIME NULL,
  `eta_horas_estimado` DECIMAL(8,2) NULL,
  `eta_calculado_em` DATETIME NULL,
  `prazo_entrega_original` DATETIME NULL,
  `limite_inicio_impressao` DATETIME NULL,
  `prioridade_paga` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `tempo_maximo_espera_horas` DECIMAL(8,2) NULL,
  `buffer_prioridade_horas` DECIMAL(8,2) NULL,
  `buffer_seguranca_horas` DECIMAL(8,2) NULL,
  `tempo_exec_farm_horas` DECIMAL(8,2) NULL,
  `dimensao_x_mm` DECIMAL(8,2) NULL,
  `dimensao_y_mm` DECIMAL(8,2) NULL,
  `dimensao_z_mm` DECIMAL(8,2) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_pedidos_fila` (`status`, `prioridade_paga`, `created_at`, `id`),
  KEY `idx_pedidos_usuario_created_at` (`id_usuario`, `created_at`),
  KEY `idx_pedidos_material` (`id_material`),
  KEY `idx_pedidos_qualidade` (`id_qualidade`),
  KEY `idx_pedidos_arquivo` (`id_arquivo`),
  KEY `idx_pedidos_prazo_entrega` (`prazo_entrega`),
  KEY `idx_pedidos_limite_inicio_impressao` (`limite_inicio_impressao`),
  CONSTRAINT `fk_pedidos_usuario` FOREIGN KEY (`id_usuario`) REFERENCES `usuarios` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_pedidos_material` FOREIGN KEY (`id_material`) REFERENCES `materiais` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_pedidos_qualidade` FOREIGN KEY (`id_qualidade`) REFERENCES `qualidades` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_pedidos_arquivo` FOREIGN KEY (`id_arquivo`) REFERENCES `arquivos` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_pedidos_preco_nonnegative` CHECK (`preco` >= 0),
  CONSTRAINT `chk_pedidos_quantidade_positive` CHECK (`quantidade` > 0),
  CONSTRAINT `chk_pedidos_tempo_estimado_nonnegative` CHECK (`tempo_estimado_s` IS NULL OR `tempo_estimado_s` >= 0),
  CONSTRAINT `chk_pedidos_material_gramas_nonnegative` CHECK (`material_gramas` IS NULL OR `material_gramas` >= 0),
  CONSTRAINT `chk_pedidos_score_complexidade_range` CHECK (`score_complexidade` IS NULL OR `score_complexidade` BETWEEN 0 AND 1),
  CONSTRAINT `chk_pedidos_preco_base_nonnegative` CHECK (`preco_base` IS NULL OR `preco_base` >= 0),
  CONSTRAINT `chk_pedidos_taxa_complexidade_nonnegative` CHECK (`taxa_complexidade` IS NULL OR `taxa_complexidade` >= 0),
  CONSTRAINT `chk_pedidos_taxa_stripe_nonnegative` CHECK (`taxa_stripe` IS NULL OR `taxa_stripe` >= 0),
  CONSTRAINT `chk_pedidos_tempo_gcode_nonnegative` CHECK (`tempo_gcode_horas` IS NULL OR `tempo_gcode_horas` >= 0),
  CONSTRAINT `chk_pedidos_prazo_horas_nonnegative` CHECK (`prazo_entrega_horas` IS NULL OR `prazo_entrega_horas` >= 0),
  CONSTRAINT `chk_pedidos_eta_horas_nonnegative` CHECK (`eta_horas_estimado` IS NULL OR `eta_horas_estimado` >= 0),
  CONSTRAINT `chk_pedidos_prioridade_boolean` CHECK (`prioridade_paga` IN (0, 1)),
  CONSTRAINT `chk_pedidos_tempo_espera_nonnegative` CHECK (`tempo_maximo_espera_horas` IS NULL OR `tempo_maximo_espera_horas` >= 0),
  CONSTRAINT `chk_pedidos_buffer_prioridade_nonnegative` CHECK (`buffer_prioridade_horas` IS NULL OR `buffer_prioridade_horas` >= 0),
  CONSTRAINT `chk_pedidos_buffer_seguranca_nonnegative` CHECK (`buffer_seguranca_horas` IS NULL OR `buffer_seguranca_horas` >= 0),
  CONSTRAINT `chk_pedidos_tempo_exec_nonnegative` CHECK (`tempo_exec_farm_horas` IS NULL OR `tempo_exec_farm_horas` >= 0),
  CONSTRAINT `chk_pedidos_dimensao_x_nonnegative` CHECK (`dimensao_x_mm` IS NULL OR `dimensao_x_mm` >= 0),
  CONSTRAINT `chk_pedidos_dimensao_y_nonnegative` CHECK (`dimensao_y_mm` IS NULL OR `dimensao_y_mm` >= 0),
  CONSTRAINT `chk_pedidos_dimensao_z_nonnegative` CHECK (`dimensao_z_mm` IS NULL OR `dimensao_z_mm` >= 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
