CREATE TABLE `impressoras` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `modelo` VARCHAR(120) NOT NULL,
  `possui_cfs` TINYINT(1) NOT NULL DEFAULT 0,
  `largura_mesa_mm` DECIMAL(8,2) NOT NULL,
  `profundidade_mesa_mm` DECIMAL(8,2) NOT NULL,
  `status` ENUM(
    'Ociosa',
    'Reservada',
    'Imprimindo',
    'Pausada',
    'Indisponivel',
    'Aguardando Remoção',
    'Erro',
    'Manutenção'
  ) NOT NULL DEFAULT 'Ociosa',
  `ip` VARCHAR(45) NULL,
  `base_url` VARCHAR(255) NULL,
  `api` ENUM('OCTOPRINT', 'MOONRAKER', 'DUMMY') NOT NULL DEFAULT 'DUMMY',
  `api_key` VARCHAR(255) NULL,
  `timeout_ms` INT UNSIGNED NOT NULL DEFAULT 15000,
  `status_fisico` VARCHAR(120) NULL,
  `job_remoto_id` VARCHAR(255) NULL,
  `ultimo_erro` TEXT NULL,
  `ultima_sincronizacao` DATETIME NULL,
  `id_pedido_atual` INT UNSIGNED NULL,
  `eficiencia` DECIMAL(5,2) NOT NULL DEFAULT 1.00,
  `taxa_erro_recente` DECIMAL(5,4) NOT NULL DEFAULT 0.0000,
  `tempo_para_ficar_livre_horas` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  `capacidade_dia_horas` DECIMAL(8,2) NOT NULL DEFAULT 8.00,
  `horas_usadas_hoje` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  `data_referencia_capacidade` DATE NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_impressoras_nome` (`nome`),
  UNIQUE KEY `uq_impressoras_id_pedido_atual` (`id_pedido_atual`),
  KEY `idx_impressoras_status` (`status`),
  CONSTRAINT `fk_impressoras_pedido_atual` FOREIGN KEY (`id_pedido_atual`) REFERENCES `pedidos` (`id`) ON DELETE SET NULL ON UPDATE RESTRICT,
  CONSTRAINT `chk_impressoras_possui_cfs_boolean` CHECK (`possui_cfs` IN (0, 1)),
  CONSTRAINT `chk_impressoras_largura_mesa_positive` CHECK (`largura_mesa_mm` > 0),
  CONSTRAINT `chk_impressoras_profundidade_mesa_positive` CHECK (`profundidade_mesa_mm` > 0),
  CONSTRAINT `chk_impressoras_timeout_positive` CHECK (`timeout_ms` > 0),
  CONSTRAINT `chk_impressoras_eficiencia_positive` CHECK (`eficiencia` > 0),
  CONSTRAINT `chk_impressoras_taxa_erro_range` CHECK (`taxa_erro_recente` BETWEEN 0 AND 1),
  CONSTRAINT `chk_impressoras_tempo_livre_nonnegative` CHECK (`tempo_para_ficar_livre_horas` >= 0),
  CONSTRAINT `chk_impressoras_capacidade_positive` CHECK (`capacidade_dia_horas` > 0),
  CONSTRAINT `chk_impressoras_horas_usadas_nonnegative` CHECK (`horas_usadas_hoje` >= 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
